site_name: HollowR00t's Machine Hacking
site_description: Writeups Machines
site_author: HollowR00t

repo_name: HollowR00t/MachineHacking
repo_url: https://github.com/HollowR00t/MachineHacking

theme:
  name: material
  logo: https://github.com/HollowR00t.png
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    #- navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - callouts

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css
